def treeShape():
    print('           *')
    print('          ***')
    print('         ****')
    print('        ******')
    print('      **********')
    print('        ******')
    print('      **********')
    print('    **************')
    print('   *****************')
    print('          **')
    print('          **')
    print('          **')
    print('          **')
    print('          **')
    print('          **')
    print('          **')
    print('          **')
    print('          **')


treeShape()